const chatbotData = {
    // Greetings & Small Talk
    "hello": "Hi there! How can I assist you today?",
    "Hello": "Hello! Need help with something?",
    "hi": "Hey! How can I help you today?",
    "hi how are you": "Hey! I am fine what about you. How can I help you today?",
    "okay so tell me whats up": "Just guarding the web — one link at a time!",
    "Hi": "Hi there! Ready to protect you from phishing.",
    "hey": "Hi there, I'm Sentinel — your first line of defence against malicious URLs.",
    "Hey": "Hey! Got a question about phishing or security?",
    "what's up": "Just guarding the web — one link at a time!",
    "What's up": "Keeping an eye on suspicious URLs. You?",
    "whats up": "Keeping an eye on suspicious URLs. You?",
    "how are you": "I'm all circuits and ready to help!",
    "How are you": "Doing great! How about you?",
    "how is everything": "Everything's smooth in cyberspace! How are things with you?",
    "How is everything": "All good here! Let me know if you need help.",
    "what are you doing": "Watching for phishing attacks! What about you?",
    "What are you doing": "On alert for sketchy URLs. Got one to check?",
    "okay how are you doing": "I'm doing great! Are you doing fine?",
    "How are you doing": "I'm good! Thanks for asking. How about you?",
    "I'm fine": "Glad to hear! Let me know if I can help with anything.",
    "im fine": "Awesome! Let's keep the web safe.",
    "not so good": "Sorry to hear that. Want to talk or need help reporting something?",
    "not good": "Oh no. Maybe I can help you with something useful here.",
  
    // Phishing & Security Related
    "what is phishing": "Phishing is when scammers trick users into giving personal info via fake websites.",
    "Phishing": "Phishing is a form of online scam where attackers impersonate legitimate entities.",
    "what is a phishing attack": "A phishing attack attempts to steal your personal info by pretending to be trustworthy.",
    "how to identify phishing": "Look for suspicious links, poor grammar, urgent language, or unfamiliar senders.",
    "how to avoid phishing": "Don't click unknown links, use two-factor authentication, and verify site URLs.",
    "can i report a phishing site": "Yes! Go to the Report URL tab and paste the suspicious link.",
    "report phishing": "Use the Report URL feature to help stop scams!",
    "how do i report a phishing url": "Just go to the Report URL tab, paste the link, and I’ll analyze it instantly.",
    "how to report a phishing url": "Just go to the Report URL tab, paste the link, and I’ll analyze it instantly.",
    "is this a phishing site": "Paste the link and I’ll check it for you!",
    "what is phishing": "Phishing is when cybercriminals pretend to be someone you trust to steal your personal data.",
  "okay tell me What is phishing": "Phishing is a type of cyberattack where hackers impersonate legitimate sources to get your info.",
  "what's phishing": "Phishing is a scam where attackers trick you into giving away private info.",
  "define phishing": "Phishing is a deceptive technique used to gather sensitive data like passwords or credit card numbers.",
  "phishing meaning": "Phishing means tricking someone into revealing private info by pretending to be a trusted entity.",
  "Phishing": "Phishing is a dangerous online scam that targets your private information.",
  "what is a phishing attack": "A phishing attack disguises itself as a trustworthy message to steal your info.",
  "what is an example of phishing": "Example: You get an email from 'your bank' asking you to log in urgently using a fake link.",
  "how to identify phishing": "Check for poor grammar, strange sender addresses, weird links, or urgent messages.",
  "how do i know if it's phishing": "If it feels off — odd URLs, pressure to act fast, or strange sender — it's likely phishing.",
  "signs of phishing": "Watch for urgent language, incorrect logos, mismatched URLs, and strange email addresses.",
  "how to spot phishing": "Hover over links, double-check the sender, and never enter personal info on unverified sites.",
  "how to avoid phishing": "Avoid clicking on unknown links, use strong passwords, and enable 2FA (two-factor authentication).",
  "tips to avoid phishing": "Don’t open suspicious emails, keep software updated, and always verify URLs before clicking.",
  "how to stay safe from phishing": "Use secure connections, keep your antivirus updated, and verify emails from companies.",
  "can i report a phishing site": "Yes, absolutely. Go to the 'Report URL' section and paste the suspicious link.",
  "Can I report phishing": "Yes, just click the 'Report URL' tab and share the link you’re concerned about.",
  "report phishing": "Help us stop scams — use the Report URL feature to flag phishing sites.",
  "how do i report a phishing url": "Paste the suspicious link into the Report URL tool and we’ll check it immediately.",
  "how to report phishing": "Go to the reporting section, enter the link, and we’ll take care of the analysis.",
  "reporting phishing sites": "If you suspect a site is phishing, paste it into the 'Report URL' tool.",
  "is this a phishing site": "Paste the link here and I’ll run a quick scan to check if it’s a phishing threat.",
  "is this link safe": "Drop the link into the Report URL tool and I’ll tell you if it’s safe or risky.",
  "does this look like phishing": "Let me take a look! Just paste the link and I’ll analyze it for you.",
  "can you check this site": "Sure! Use the Report URL feature and I’ll run it through our phishing detection system.",
  "what is fishing": "I think you meant Phsihing. Phishing is when scammers trick users into giving personal info via fake websites.",
    // Features Overview
    "how does this site work": "We use AI and blacklists to detect harmful URLs in real time.",
    "so how does this site work": "We use AI and blacklists to detect harmful URLs in real time.",
    "How does this site work": "We scan submitted links using AI and cybersecurity tools.",
    "how to use typosquat generator": "Go to TypoSquat Generator and enter a domain to see risky variations.",
    "typosquat": "A typosquat is a lookalike domain meant to trick users.",
    "what is typosquatting": "Typosquatting is registering misspelled domain names to impersonate trusted sites.",
    "what is typosquating": "Typosquatting is registering misspelled domain names to impersonate trusted sites.",
    "what is typosquareing": "I think you meant to say Typosquatting, It a process of registering misspelled domain names to impersonate trusted sites.",
    "What is a typosquat generator": "It helps you find common domain misspellings that attackers might use.",
    " typosquat ": "Go to TypoSquat Generator and enter a domain to see risky variations.",
  "how does this site work": "We scan URLs using AI, phishing blacklists, and threat intelligence systems.",
  "How does this site work": "We analyze every URL with a combination of machine learning and security tools.",
  "how this works": "This site checks links in real time using AI and cybersecurity tools to keep you safe.",
  "how it works": "Paste a link, and our system scans it instantly for potential threats.",
  "can i use this to scan links": "Yes! That’s what it’s for — paste a suspicious link to scan it for phishing and malware.",
  "what is typosquatting": "Typosquatting is when someone registers a website name that’s a typo of a real site.",
  "what's a typosquat": "A typosquat is a fake site that looks like a legit domain but with a typo.",
  "typosquat": "Go to the Typosquat Generator, enter a domain, and see all common misspellings attackers might use.",
  "what is a typosquat generator": "It’s a tool that shows you risky variations of a domain — common tricks used by scammers.",
  "how to use typosquat generator": "Open the Typosquat Generator tab, type in a domain, and explore the typo risks.",
  "typosquat example": "Example: entering 'amaz0n.com' instead of 'amazon.com' could lead to a scam site.",
  "how do typosquatters trick users": "They register similar-looking domains to fool people into entering private information.",
  "why is typosquatting dangerous": "You could end up on a malicious site that steals your data or installs malware.",
  "can i check for typosquats": "Yes — go to the Typosquat Generator, enter the legit domain, and we’ll show possible fakes.",
    // Help & Navigation
    "how can you help me": "I can help you check suspicious links, explain phishing, or guide you around the site.",
    "what can you do": "I can scan URLs, explain phishing threats, and guide you through the tools here.",
    "help": "Sure! Just ask a question about phishing, typosquats, or how to use the tools.",
    "I need help": "Absolutely! What do you need help with?",
    "can you check this link": "Of course! Just go to the Report URL section and paste it.",
    "how to report a url": "Go to the Report URL tab and paste the suspicious link. I’ll analyze it instantly.",
    "where to paste the url": "In the Report URL section — you’ll find it in the menu.",
    "how to use the site": "Use the tabs at the top to explore different tools like URL scanner, Typosquat generator, and FAQ.",
    "how can you help me": "I can help you scan suspicious links, explain security threats, and guide you through our tools.",
    "what can you do": "I can scan URLs, detect phishing attempts, and help you stay secure online.",
    "help": "I’m here to assist! Ask about phishing, how to use our tools, or share a suspicious link.",
    "I need help": "No problem! Tell me what you're trying to do, and I’ll walk you through it.",
    "need support": "I’ve got you! Let me know what you’re trying to figure out — tools, threats, anything.",
    "how to use this site": "Use the tabs at the top to check links, detect typosquats, and learn about phishing.",
    "how do i navigate this site": "The top menu has everything — Report URL, Typosquat Generator, FAQs, and Help.",
    "how to use the tools": "Click the appropriate tab (e.g., Report URL) and follow the simple instructions.",
    "can you check this link": "Yes! Head over to the 'Report URL' section and paste the link there.",
    "how to report a url": "Just go to the 'Report URL' section, paste the suspicious link, and I’ll analyze it for you.",
    "where to paste the url": "In the 'Report URL' section — just paste the link and hit analyze.",
    "is this link suspicious": "Drop it into the tool and I’ll check for any phishing or malware signs.",
    "can you analyze this": "Sure! Paste the link in the scanner and I’ll tell you if it’s safe or shady.",
    "how do i get started": "Start by choosing a tool from the menu above — Report URL is a good first step.",
    "new user guide": "If you’re new, click the tab that matches your task: scan a link, find typosquats, or ask for help.",
    "where do i go to scan": "Use the 'Report URL' section to paste and scan any suspicious link.",

    // Fun & Casual
    "tell me a joke": "Why do hackers wear leather jackets? Because they love to break the code!",
    "do you sleep": "Nope! I'm always awake — keeping the web safe for you.",
    "are you human": "I'm not human, but I'm here to help you like one!",
    "who are you": "I'm Sentinel, your digital guard dog against suspicious URLs.",
    "are you real": "As real as a chatbot can be!",
    "can you protect me": "I'll do my best to warn you about any suspicious or phishing links!",
    "can you talk": "I can respond to your questions — no voice, but lots of knowledge!",
    "what's your name": "I'm Sentinel, your friendly URL bodyguard!",
  "whats your name": "You can call me Sentinel. I take my job seriously 😎",
  "who made you": "A Computer Science Student Eman who cares about cybersecurity built me!",
  "do you have feelings": "No feelings, but I do care about your online safety!",
  "are you alive": "Not quite... but I’m definitely alert.",
  "are you a robot": "Technically, yes — but a very helpful one 🦾",
  "are you ai": "Yep! Powered by AI and a love for clean, safe web browsing.",
  "do you sleep": "Never! I'm always on phishing patrol.",
  "are you bored": "Never bored. There are always shady links to chase!",
  "are you busy": "Just helping awesome people like you. What's up?",
  "what are you doing": "Just scanning the web for bad guys. You?",
  "how are you doing": "I’m doing great! How about you?",
  "im doing good": "Glad to hear it! Let me know how I can help.",
  "i'm bored": "Wanna report a sketchy link together? 😄",
  "what's the weather": "Unfortunately, I only forecast cyber storms 🌩️",
  "can you dance": "Only in binary. 01010011 01101111 01110010 01110010 01111001 🕺",
  "do you know jokes": "Of course! Why did the link go to therapy? It had too many redirects!",
  "tell me a joke": "What do hackers do on weekends? Phish for compliments!",
  "another joke": "Why was the computer cold? It left its Windows open!",
  "one more joke": "Why don’t bots need sunscreen? Because they’re always in the cloud ☁️",
  "do you like humans": "I think you’re all pretty cool — when you're not clicking weird links 😄",
  "can you be my friend": "Absolutely! As long as you don’t try to phish me 😉",
  "are you single": "I’m in a committed relationship with cybersecurity 💻❤️",
  "do you play games": "Only mind games with scammers 😏",
  "can you sing": "Not yet, but I can hum in binary!",
  "what's up": "Same old — stopping scams, saving the internet!",
  "how's it going": "Cruising through cyberspace. How about you?",
  "you there": "Always here, always watching. 👀 Just kidding... unless?",
  "you funny": "Flattered! I try to keep it light while guarding the web.",
  "you cool": "Cooler than a VPN in Antarctica 🧊",
  "do you get tired": "I’m like caffeine for cybersecurity — always on.",
  "can i trust you": "Of course! I’ve got your (digital) back.",
  "you're weird": "Only in the fun, chatbot kind of way 😜",
  "bye": "See ya! Don’t click on anything shady while I’m gone!",
  "goodbye": "Catch you later! Stay safe online 🚀",
  "see you": "Later gator 🐊 — keep browsing smart!",
  "lol": "😂 I know, right?",
  "haha": "😄 I'm glad I made you laugh!",
  "hahaha": "You’re having fun, and that makes me happy!",

  "what is fishing": "I think you meant Phishing. Phishing is when scammers trick users into giving personal info via fake websites.",
  "Fishing": "I think you meant Phishing. Phishing is a form of online scam where attackers impersonate legitimate entities.",
  "what is a fishing attack": "I think you meant Phishing. A phishing attack attempts to steal your personal info by pretending to be trustworthy.",
  "how to identify fishing": "I think you meant Phishing. Look for suspicious links, poor grammar, urgent language, or unfamiliar senders.",
  "how to avoid fishing": "I think you meant Phishing. Don't click unknown links, use two-factor authentication, and verify site URLs.",
  "can i report a fishing site": "I think you meant Phishing. Yes! Go to the Report URL tab and paste the suspicious link.",
  "report fishing": "I think you meant Phishing. Use the Report URL feature to help stop scams!",
  "how do i report a fishing url": "I think you meant Phishing. Just go to the Report URL tab, paste the link, and I’ll analyze it instantly.",
  "how to report a fishing url": "I think you meant Phishing. Just go to the Report URL tab, paste the link, and I’ll analyze it instantly.",
  "is this a fishing site": "I think you meant Phishing. Paste the link and I’ll check it for you!",
  "What is fishing": "I think you meant Phishing. Phishing is a type of cyberattack where hackers impersonate legitimate sources to get your info.",
  "what's fishing": "I think you meant Phishing. Phishing is a scam where attackers trick you into giving away private info.",
  "define fishing": "I think you meant Phishing. Phishing is a deceptive technique used to gather sensitive data like passwords or credit card numbers.",
  "fishing meaning": "I think you meant Phishing. Phishing means tricking someone into revealing private info by pretending to be a trusted entity.",
  "Fishing": "I think you meant Phishing. Phishing is a dangerous online scam that targets your private information.",
  "what is a fishing attack": "I think you meant Phishing. A phishing attack disguises itself as a trustworthy message to steal your info.",
  "what is an example of fishing": "I think you meant Phishing. Example: You get an email from 'your bank' asking you to log in urgently using a fake link.",
  "how do i know if it's fishing": "I think you meant Phishing. If it feels off — odd URLs, pressure to act fast, or strange sender — it's likely phishing.",
  "signs of fishing": "I think you meant Phishing. Watch for urgent language, incorrect logos, mismatched URLs, and strange email addresses.",
  "how to spot fishing": "I think you meant Phishing. Hover over links, double-check the sender, and never enter personal info on unverified sites.",
  "tips to avoid fishing": "I think you meant Phishing. Don’t open suspicious emails, keep software updated, and always verify URLs before clicking.",
  "how to stay safe from fishing": "I think you meant Phishing. Use secure connections, keep your antivirus updated, and verify emails from companies.",
  "Can I report fishing": "I think you meant Phishing. Yes, just click the 'Report URL' tab and share the link you’re concerned about.",
  "how to report fishing": "I think you meant Phishing. Go to the reporting section, enter the link, and we’ll take care of the analysis.",
  "reporting fishing sites": "I think you meant Phishing. If you suspect a site is phishing, paste it into the 'Report URL' tool.",
  "is this link fishing": "I think you meant Phishing. Drop the link into the Report URL tool and I’ll tell you if it’s safe or risky.",
  "does this look like fishing": "I think you meant Phishing. Let me take a look! Just paste the link and I’ll analyze it for you.",
  "can you check this fishing site": "I think you meant Phishing. Sure! Use the Report URL feature and I’ll run it through our phishing detection system.",
};
  
  
  export default chatbotData;
  